(function(){'use strict';
var key='bonzanini_consent_v1', maxAge=183*24*60*60*1000, saved=null, state={analytics:false,media:false},mediaLoaded=false;
try{saved=JSON.parse(localStorage.getItem(key));if(!saved||Date.now()-saved.at>=maxAge||typeof saved.analytics!=='boolean'||typeof saved.media!=='boolean')saved=null;}catch(e){saved=null;}
if(saved)state={analytics:saved.analytics,media:saved.media};
window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments);};
window.gtag('consent','default',{analytics_storage:state.analytics?'granted':'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});
window.gtag('js',new Date());window.gtag('config','G-F3P5SE0XL8',{send_page_view:true});
var tag=document.createElement('script');tag.async=true;tag.src='https://www.googletagmanager.com/gtag/js?id=G-F3P5SE0XL8';document.head.appendChild(tag);
function media(){if(mediaLoaded)return;mediaLoaded=true;document.querySelectorAll('iframe[data-consent-src]').forEach(function(f){f.src=f.getAttribute('data-consent-src');f.hidden=false;});document.querySelectorAll('.media-placeholder').forEach(function(p){p.hidden=true;});var widget=document.getElementById('JFWebsiteWidget-019c4d624b4577ebadf7f242b8a1ac3b2d12');if(widget){var w=document.createElement('script');w.src='https://eu.jotform.com/website-widgets/embed/019c4d624b4577ebadf7f242b8a1ac3b2d12';w.defer=true;widget.parentNode.appendChild(w);}var font=document.createElement('link');font.rel='stylesheet';font.href='https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500&family=Montserrat:wght@300;400;500;600&display=swap';document.head.appendChild(font);}
function show(){document.getElementById('cookie-panel').hidden=false;document.getElementById('consent-analytics').checked=state.analytics;document.getElementById('consent-media').checked=state.media;}
function save(a,m){var previous=state,next={analytics:a,media:m,at:Date.now()};try{localStorage.setItem(key,JSON.stringify(next));}catch(e){}document.getElementById('cookie-panel').hidden=true;if((previous.analytics&&!a)||(previous.media&&!m)){window.gtag('consent','update',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});location.reload();return;}state={analytics:a,media:m};window.gtag('consent','update',{analytics_storage:a?'granted':'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});if(a&&!previous.analytics)window.gtag('event','page_view',{page_location:location.href,page_title:document.title});if(m)media();}
document.getElementById('consent-all').addEventListener('click',function(){save(true,true);});document.getElementById('consent-none').addEventListener('click',function(){save(false,false);});document.getElementById('consent-save').addEventListener('click',function(){save(document.getElementById('consent-analytics').checked,document.getElementById('consent-media').checked);});document.querySelectorAll('.open-cookie-settings').forEach(function(b){b.addEventListener('click',show);});document.querySelectorAll('a[href*="wa.me/"],a[href*="api.whatsapp.com/"]').forEach(function(link){link.addEventListener('click',function(){if(!state.analytics)return;window.gtag('event','contact',{contact_method:'whatsapp',link_url:link.getAttribute('href'),page_location:location.href,page_title:document.title});});});if(state.media)media();if(!saved)show();})();